### ISSUE TITLE
A grey artificial border appears after pixelation

### ISSUE THREAD

**Issue by DarkAdaNFT** [giventofly/pixelit#15]
Hi,
thanks for creating such a nice tool!

I have tested the tool and most of it works nicely. However for some reason I always get this weird artifical border which was not there in the original png. See image below.
Do you know what the problem might be?

![grafik](https://user-images.githubusercontent.com/94016695/151886057-99520555-3477-429e-9957-ef98e461170d.png)

Best regards!

**Comment by giventofly** [comment]
Hi,
can you provide me the original image? (Or any image where this happens so I can replicate it?)

**Comment by DarkAdaNFT** [comment]
Hi, thanks for getting back so quickly. Basically happens with every image when I lower the block size. The lower I go the larger the grey border gets (it's always at the bottom or the right side). 
Here is an example (but basically happens to any image) that you can try on.


Thanks a lot!


![Example1](https://user-images.githubusercontent.com/94016695/151893608-6c6315f3-08da-4fa3-a03c-18072bbed436.png)

**Comment by DarkAdaNFT** [comment]
Hi, did you have time to check the issue? 

Thanks in advance!

**Comment by giventofly** [comment]
Hi, not yet. It is not forgotten, I will try to make a fix for that, can't give you an estimate when I will have it done, but soon.

Just out of curiosity, do you mint NFTs on Cardano ?

**Comment by DarkAdaNFT** [comment]
Cool, thank. Much appreciated!

Yes, I have minted few just to try it out and explore that a bit. But I want start again soon with a more detailed concept.

**Comment by giventofly** [comment]
All right, fixed that issue and also added some new palettes. Give it a try please so I can close this issue.

**Comment by DarkAdaNFT** [comment]
Yes, works perfectly now. Thanks.
