### ISSUE TITLE
Website: change palette 

### ISSUE THREAD

**Issue by Stazy805** [giventofly/pixelit#16]
I have been using your web site to make NFT’s and have been using the change palette option and was having trouble with clicking the button until I get the palette I want. So therefore can u make it where there’s a scroll down with all the palettes and you can just click on which ever palette  u want

**Comment by giventofly** [comment]
Hi,

sure, makes sense to improve the UX I will do it as soon as I have some free time. Thank you for the feedback

**Comment by giventofly** [comment]
Updated github page with scroll down palette selector
