### ISSUE TITLE
bug: wrong image size

### ISSUE THREAD

**Issue by bakeiro** [giventofly/pixelit#19]
Hi!

me again 😅, I was working with your tool, but seems that I have some issues when I try to pixelate a small image (250x250) as you can see in the attachment, the image it's not properly displayed (the right/bottom side of it it's cropped)

<img width="659" alt="image" src="https://user-images.githubusercontent.com/16777161/156359503-c2281f29-8d4e-4f08-b20d-3af669ad9516.png">

**Comment by giventofly** [comment]
I fixed some additional artifacts for bigger images and added a bug for smaller ones :)

Give me some time and I'll fix it and make a tests page to avoid errors

**Comment by giventofly** [comment]
Should be fixed now, reopen please if it is not with an example image. thanks
