### ISSUE TITLE
palette can't limit color

### ISSUE THREAD

**Issue by mm7mm7mm7** [giventofly/pixelit#25]
block 80 X80 = 6400
<a href="https://ibb.co/dcbj6GG"><img src="https://i.ibb.co/KGNb7FF/A7-R-6-YMC61-KLFBK-HG7-V.png" alt="A7-R-6-YMC61-KLFBK-HG7-V" border="0"></a>

I exported the color , and Paste on excel duplicates , I tested about 200-600 color , But I only set 30 palette 

<a href="https://ibb.co/3mfyg2n"><img src="https://i.ibb.co/DfGD0hZ/123.png" alt="123" border="0"></a>

how can i limit color??

**Comment by giventofly** [comment]
I don't understand your problem/question

**Comment by mm7mm7mm7** [comment]
For example, I used it palette have 8  color ,I convert jpg to pixel art , Normal pixel art will only use the 8 colors of the palette
<a href="https://imgbb.com/"><img src="https://i.ibb.co/HrpTTxg/1231.png" alt="1231" border="0"></a>
but i test some pixel art  have 200-600 color

**Comment by giventofly** [comment]
Can you give a image as example? I currently don't have time to work on
this, unless it is a quick thing to do

A domingo, 17/07/2022, 11:04, mm7mm7mm7 ***@***.***> escreveu:
