### ISSUE TITLE
Can't customize colors in the palette, considering adding this feature?

### ISSUE THREAD

**Issue by zousiyu1995** [giventofly/pixelit#27]
Can't customize colors in the palette, I can only select presets, considering adding this feature?

**Comment by giventofly** [comment]
Hi,

you can customize your colors if you want to (read documentation here https://github.com/giventofly/pixelit ) but you need to do it in your machine. I currently don't have time to make a palette selector for the example/demo page.

Maybe in the future, currently don't have time, but feel free to create a pull request with your palette and I can merge it (if it is different enough).
