### ISSUE TITLE
Instructions on usage unclear

### ISSUE THREAD

**Issue by Serif-7** [giventofly/pixelit#31]
Firstly, great project.

I'm primarily a Lua and Python dev and don't deal with JS that much, so I don't know how to use this tool locally. All I want to do is just use a custom palette to pixelate an image. I have the repo cloned and `npm install`'ed but am unsure how to actually point it at a jpg and get a result. I don't see anywhere in `src/main.js` to add in a file name.

Some extra info on how to use this would be greatly appreciated, if you have some time. Thanks.

**Comment by giventofly** [comment]
Hi and thanks!

You always need a browser to generate the image (it is canvas generated), I made a test page specially for people that need some guidance or want to do some batch processing.

[Tests page](https://giventofly.github.io/pixelit/tests.html) and the [js to generate multiple images](https://github.com/giventofly/pixelit/blob/master/docs/js/tests.js).
