### ISSUE TITLE
Can we added custom palette?

### ISSUE THREAD

**Issue by wiekniera** [giventofly/pixelit#33]
Hey guys,
Just wondering if we can use our own preset custom palette?
Can you guys add feature to add custom palette? I really like pixelit
Many Thanks !

**Comment by giventofly** [comment]
The webpage was just an example of it working, was never intended to work as the full app, but that feature seems kind of fun to implement. 

If I have some free time in the next days I'll add that option.

**Comment by wiekniera** [comment]
Thanks for your effort man ! really appreciate it, your webpage are simple, easy and i love the result.
I really want to use from this comunnity palette : https://lospec.com/palette-list

**Comment by giventofly** [comment]
I really like that site, I used to go there a bit when I was learning/reading about pixel art.

Added the custom palette generator on the (live page)[https://giventofly.github.io/pixelit] :)
