### ISSUE TITLE
Thank you 

### ISSUE THREAD

**Issue by sukhchain9935** [giventofly/pixelit#4]
You haven't set up github Discussions so I'm posting it here.

**Thank you for creating this, now I can easily convert my icons into pixel icons and create pixel versions of my favorite fonts**.
Just a request, when I download the image, it contains both the original size and pixelated size on the top left corner in the same image, can you make them separate? It's fine this way too but it would be great to be able to download them separately.

**Comment by sukhchain9935** [comment]
Can I make a pull request if I'm able to do it myself?

**Comment by giventofly** [comment]
Hi, yes, sorry for the delay, didn't get a notification for this.

I will give it a look, but feel free to do PRs.

**Comment by sukhchainn** [comment]
I am using my Dell laptop with Windows 7 and Firefox browser. It works fine on it.
When I created this issue I was on Windows 10. I'll test it on Win10 and tell you if it still happens.

Thanks again for this tool.

**Comment by giventofly** [comment]
Hi,

took me sometime to find be able to replicate the problem but found it was when the image had transparency. Released a new fixed version :)

Updated all the files and the live version should be working.
