### ISSUE TITLE
Amazing tool - one edit

### ISSUE THREAD

**Issue by JoeydevriesNL** [giventofly/pixelit#5]
Is it possible to remove the small image from the top left in the field, so it doesn't come  with the download? 
![image](https://user-images.githubusercontent.com/46714256/115017143-5c9d9600-9eb6-11eb-9f8a-89dc7d3d9074.png) let me know! :)

Overall amazing tool!

**Comment by giventofly** [comment]
Hi,

took me sometime to find be able to replicate the problem but found it was when the image had transparency. Released a new fixed version :)

Updated all the files and the live version should be working.

**Comment by JoeydevriesNL** [comment]
Nice and quick fix thanks!
