### ISSUE TITLE
Incomplete render on larger images

### ISSUE THREAD

**Issue by ptrrdrck** [giventofly/pixelit#6]
Hey, I've noticed the pixelized renders are incomplete for more detailed combinations of resolution/file size/block size. Happy to see this git active!

**Comment by giventofly** [comment]
Hi,

can you give me more details on what you mean? and if possible an example?

**Comment by ptrrdrck** [comment]
Ok for example, with the following image, any renders with a block size > 5 do not fully render. The unrendered portion is transparent in the .png image.

![nyc-no-love](https://user-images.githubusercontent.com/56177908/115126615-4ec34000-9f9e-11eb-9975-7b2c2a1c4807.jpeg)

**Comment by giventofly** [comment]
Hi again,

found the problem and fixed it, also change a bit the scale when image is a bit big to get better results. 

Thanks for the feedback.
