### ISSUE TITLE
Palette isn't being applied to image

### ISSUE THREAD

**Issue by eliraybon** [giventofly/pixelit#7]
Apologies if this isn't the correct place to post this or if I'm overlooking something simple...

I'm attempting to generate an image with a custom palette. I'm getting a pixelated image, but the colors are the same as the original image. 

Here's my code: 

```
<html>
  <head title="Generate Pixel Art"></head>
  <body>
    <img src="assets/myimage.jpg" id="pixelitimg" alt="">
    <canvas id="pixelitcanvas"></canvas>
    <script src="dist/pixelit.js"></script>
    <script>
        const drawImage = () => {
          const mypalette = [
          [0, 255, 0], [0, 100, 0], [0, 150, 0], [0, 200, 0]
          ];
          const px = new pixelit({
              from:  document.getElementById('pixelitimg'), 
              palette: mypalette, 
              scale: 16
            });
          px.draw().pixelate().convertPalette(); 
        }
        setTimeout(drawImage, 100)
    </script> 
  </body>
</html>
```

Does anything jump out as wrong here? 

Note: Without putting the code in a callback and using setTimeout I was getting a blank page. 

Thanks!!

**Comment by giventofly** [comment]
Hi, 
okay I gave it a look. You are needing the timeout because you are trying to process and image that hasn't been loaded on the page yet. You can put a listener from when it loads to use the function drawImage, like this:

`document.getElementById('pixelitimg').addEventListener('load',drawImage);`

This solves the use of the timeout. I've created an test.html and copy pasted your code and everything worked, my test.html inside de /docs folder after cloning the repository:

`<html>
  <head title="Generate Pixel Art"></head>
  <body>
    <img src="assets/sky.jpg" id="pixelitimg" alt="">
    <canvas id="pixelitcanvas"></canvas>
    <script src="../dist/pixelit.js"></script>
    <script>
        const drawImage = () => {
          const mypalette = [
          [0, 255, 0], [0, 100, 0], [0, 150, 0], [0, 200, 0]
          ];
          const px = new pixelit({
              from:  document.getElementById('pixelitimg'), 
              palette: mypalette, 
              scale: 16
            });
          px.draw().pixelate().convertPalette(); 
        }
        document.getElementById('pixelitimg').addEventListener('load',drawImage);
        //setTimeout(drawImage, 100)
    </script> 
  </body>
</html>`

And it produced:

![image](https://user-images.githubusercontent.com/6298937/124934976-224b1d00-dffd-11eb-8a4c-2eba31ef2b42.png)

Did you get any error or something more to help find the problem?

**Comment by eliraybon** [comment]
Thanks for looking into this and getting back so quickly! That is the exact result I'm looking for! 

Before, when I was using the `setTimeout`, I wasn't getting any errors. Just a pixelated image that was the same colors as the original. 

When I copy paste your code that waits for the image to load, I'm seeing this: 
```
pixelit.js:236 Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
    at pixelit.convertPalette (file:///Users/usernam/Downloads/pixelit-master/dist/pixelit.js:236:30)
    at HTMLImageElement.drawImage (file:///Users/username/Downloads/pixelit-master/docs/test.html:17:32)
```

**Comment by giventofly** [comment]
Can you try this way:
```
  document.addEventListener("DOMContentLoaded", function () { 
        drawImage();
      });

```

**Comment by eliraybon** [comment]
Unfortunately, no difference. 
<img width="1437" alt="Screen Shot 2021-07-09 at 11 54 45 AM" src="https://user-images.githubusercontent.com/52835557/125105597-a01a3180-e0ac-11eb-8c5a-ac460ac6d796.png">

**Comment by giventofly** [comment]
That seems to be a problem of loading the image from [another server](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image)

I'm unable to replicate on my side, don't know if I can of much help at this point, but why is it trying to load from file:// instead of localhost ?

**Comment by eliraybon** [comment]
I'm not running localhost... 

I just downloaded the repo, created a `test.html` file in the `docs` folder, and opened that file in the browser. 

Do I need to do more setup?

**Comment by eliraybon** [comment]
Everything is working perfectly now! Just needed to run with localhost.

**Comment by giventofly** [comment]
Awesome, it was as I suspected the cross-origin problem. Glad it is working
