### ISSUE TITLE
Can I get the number of pixel by colour in a picture?

### ISSUE THREAD

**Issue by tehjinxi** [giventofly/pixelit#8]
<img width="1023" alt="Screenshot 2021-07-25 at 5 42 43 PM" src="https://user-images.githubusercontent.com/52269135/126894783-d40f5ff8-81d9-468e-a571-8027b194f6ea.png">

for example the above picture, I want to know how many of the pixel are in yellow and how many  of them are purple

**Comment by giventofly** [comment]
Hi, yes you can easily implement that.

for example you can use the function that converts the image to grayscale and do a count of colors, I picked it up you just need to finish it.

```countTheColors() {
    const w = this.drawto.width;
    const h = this.drawto.height;
    var imgPixels = this.ctx.getImageData(0, 0, w, h);
    //object to store the colors/values
    for (var y = 0; y < imgPixels.height; y++) {
      for (var x = 0; x < imgPixels.width; x++) {
       //track here the colors
      }
    }
    //do something with the value
    return this;
  }
 ```
Just need to fill the comments,

regards
