### ISSUE TITLE
similar effect as 

### ISSUE THREAD

**Issue by whitetornado** [giventofly/pixelit#9]
we tried this but missing details in the face. If you see https://pixel-me.tokyo/en/  and upload a image (face detection) the converting to a pixel image is so great, how they do this? and is this possible with your script??

**Comment by giventofly** [comment]
Hi, you would probably need to adjust to your needs, you can get close if you do a pallet selection based on the image colors, they also do face detection. Should be a bit better algorithm, you can probably do similar with some tweaking

**Comment by whitetornado** [comment]
hi thanks for your reply.

Op di 17 aug. 2021 om 14:21 schreef José Moreira ***@***.***>:
